# conf-PDU.yaml
# Rack PDU configuration following entity naming (rack_pdu_*)
#
# SNMP Sensors
sensor:
  - platform: snmp
    name: "Rack PDU Input Voltage"
    unique_id: rack_pdu_voltage_input
    entity_id: sensor.rack_pdu_voltage_input
    baseoid: 1.3.6.1.4.1.318.1.1.12.1.16.0
    unit_of_measurement: "V"

  - platform: snmp
    name: "Rack PDU Input Current"
    unique_id: rack_pdu_current_input
    entity_id: sensor.rack_pdu_current_input
    baseoid: 1.3.6.1.4.1.318.1.1.12.1.17.0
    unit_of_measurement: "A"

  - platform: snmp
    name: "Rack PDU Input Power"
    unique_id: rack_pdu_power_input
    entity_id: sensor.rack_pdu_power_input
    baseoid: 1.3.6.1.4.1.318.1.1.12.1.18.0
    unit_of_measurement: "W"

  - platform: snmp
    name: "Rack PDU Temperature"
    unique_id: rack_pdu_temperature
    entity_id: sensor.rack_pdu_temperature
    baseoid: 1.3.6.1.4.1.318.1.1.12.1.19.0
    unit_of_measurement: "°C"

  - platform: snmp
    name: "Rack PDU Total Load"
    unique_id: rack_pdu_total_load
    entity_id: sensor.rack_pdu_total_load
    baseoid: 1.3.6.1.4.1.318.1.1.12.1.20.0
    unit_of_measurement: "W"

# SNMP Outlet Switches
switch:
  - platform: snmp
    name: "Rack PDU Outlet 1"
    unique_id: rack_pdu_outlet_1
    entity_id: switch.rack_pdu_outlet_1
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.1

  - platform: snmp
    name: "Rack PDU Outlet 2"
    unique_id: rack_pdu_outlet_2
    entity_id: switch.rack_pdu_outlet_2
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.2

  - platform: snmp
    name: "Rack PDU Outlet 3"
    unique_id: rack_pdu_outlet_3
    entity_id: switch.rack_pdu_outlet_3
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.3

  - platform: snmp
    name: "Rack PDU Outlet 4"
    unique_id: rack_pdu_outlet_4
    entity_id: switch.rack_pdu_outlet_4
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.4

  - platform: snmp
    name: "Rack PDU Outlet 5"
    unique_id: rack_pdu_outlet_5
    entity_id: switch.rack_pdu_outlet_5
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.5

  - platform: snmp
    name: "Rack PDU Outlet 6"
    unique_id: rack_pdu_outlet_6
    entity_id: switch.rack_pdu_outlet_6
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.6

  - platform: snmp
    name: "Rack PDU Outlet 7"
    unique_id: rack_pdu_outlet_7
    entity_id: switch.rack_pdu_outlet_7
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.7

  - platform: snmp
    name: "Rack PDU Outlet 8"
    unique_id: rack_pdu_outlet_8
    entity_id: switch.rack_pdu_outlet_8
    baseoid: 1.3.6.1.4.1.318.1.1.4.4.2.1.3.8

# Template switches (use outlet description sensors if present)
template:
  - switch:
      - name: "{{ states('sensor.rack_pdu_outlet_1_description') | default('Outlet 1') }}"
        unique_id: rack_pdu_outlet_1_auto
        state: "{{ is_state('switch.rack_pdu_outlet_1', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_1
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_1

      - name: "{{ states('sensor.rack_pdu_outlet_2_description') | default('Outlet 2') }}"
        unique_id: rack_pdu_outlet_2_auto
        state: "{{ is_state('switch.rack_pdu_outlet_2', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_2
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_2

      - name: "{{ states('sensor.rack_pdu_outlet_3_description') | default('Outlet 3') }}"
        unique_id: rack_pdu_outlet_3_auto
        state: "{{ is_state('switch.rack_pdu_outlet_3', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_3
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_3

      - name: "{{ states('sensor.rack_pdu_outlet_4_description') | default('Outlet 4') }}"
        unique_id: rack_pdu_outlet_4_auto
        state: "{{ is_state('switch.rack_pdu_outlet_4', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_4
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_4

      - name: "{{ states('sensor.rack_pdu_outlet_5_description') | default('Outlet 5') }}"
        unique_id: rack_pdu_outlet_5_auto
        state: "{{ is_state('switch.rack_pdu_outlet_5', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_5
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_5

      - name: "{{ states('sensor.rack_pdu_outlet_6_description') | default('Outlet 6') }}"
        unique_id: rack_pdu_outlet_6_auto
        state: "{{ is_state('switch.rack_pdu_outlet_6', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_6
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_6

      - name: "{{ states('sensor.rack_pdu_outlet_7_description') | default('Outlet 7') }}"
        unique_id: rack_pdu_outlet_7_auto
        state: "{{ is_state('switch.rack_pdu_outlet_7', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_7
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_7

      - name: "{{ states('sensor.rack_pdu_outlet_8_description') | default('Outlet 8') }}"
        unique_id: rack_pdu_outlet_8_auto
        state: "{{ is_state('switch.rack_pdu_outlet_8', 'on') }}"
        turn_on:
          service: switch.turn_on
          target:
            entity_id: switch.rack_pdu_outlet_8
        turn_off:
          service: switch.turn_off
          target:
            entity_id: switch.rack_pdu_outlet_8
