homeassistant:
  customize: !include customize.yaml
  packages:
### APC PDU7920 Virtual Device ###############################################
    pdu: !include conf-PDU.yaml
default_config:

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

### PIONEER AVR SC-71 ##########################################################
media_player: !include conf-pioneer_avr.yaml
#
### Envisalink Duo ##########################################################
envisalink: !include conf-envisalink.yaml
#
