homeassistant:
  customize: !include customize.yaml
default_config:

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

### PIONEER AVR SC-71 ##########################################################
media_player: !include conf-pioneer_avr.yaml
#
### Envisalink Duo ##########################################################
envisalink: !include conf-envisalink.yaml
#
### APC PDU7920 Outlets ##########################################################
switch: !include conf-PDU.yaml
